services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - POSTGRES_NAME=dusangire-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=admin123
    entrypoint: ["/docker-entrypoint.sh"]
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ../dusangire-frontend
    ports:
      - "5173:5173" # Changed from 3000:5173 to 5173:5173
    volumes:
      - ../dusangire-frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:8000  # Changed from localhost to backend service name
    working_dir: /app
    command: npm run dev -- --host
    depends_on:
      - backend

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dusangire-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
