version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=dusangire-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=admin123
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dusangire-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
