version: '3.8'

services:
  frontend:
    build: ./dusangire-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./dusangire-frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:8000

  backend:
    build: ./dusangire_backend
    ports:
      - "8000:8000"
    volumes:
      - ./dusangire_backend:/app
