# Generated by Django 5.2.1 on 2025-05-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_contribution_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='transaction_id',
        ),
    ]
