# Generated by Django 5.2.1 on 2025-05-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_adminreportspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfers_Received',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_code', models.CharField(max_length=50)),
                ('donor', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('account_no', models.CharField(max_length=50)),
                ('number_of_payments', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('distributed_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
