# Generated by Django 5.2.1 on 2025-05-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_transfercomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('TRANSFER', 'Transfer'), ('MOMO', 'MoMo')], max_length=10)),
                ('transfer_option', models.CharField(blank=True, choices=[('GENERAL', 'General'), ('SPECIFIC', 'Specific')], max_length=10, null=True)),
                ('specific_sub_option', models.CharField(blank=True, choices=[('GENERAL', 'General'), ('NUMBER', 'Number'), ('INDIVIDUAL', 'Individual')], max_length=10, null=True)),
                ('momo_option', models.CharField(blank=True, choices=[('GENERAL', 'General'), ('SCHOOLS', 'Schools')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
