# Generated by Django 5.2.1 on 2025-05-30 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='momo_option',
        ),
        migrations.RemoveField(
            model_name='record',
            name='record_type',
        ),
        migrations.RemoveField(
            model_name='record',
            name='specific_sub_option',
        ),
        migrations.RemoveField(
            model_name='record',
            name='transfer_option',
        ),
        migrations.AddField(
            model_name='record',
            name='type',
            field=models.CharField(choices=[('TRANSFER', 'Transfer'), ('MOMO', 'Momo')], default='TRANSFER', max_length=20),
        ),
        migrations.CreateModel(
            name='MomoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GENERAL', 'General'), ('SCHOOL', 'School')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momo_records', to='core.record')),
                ('schools', models.ManyToManyField(blank=True, to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GENERAL', 'General (All Schools)'), ('SPECIFIC', 'Specific')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_records', to='core.record')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificTransferDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_type', models.CharField(choices=[('GENERAL', 'General'), ('NUMBER', 'Number'), ('INDIVIDUAL', 'Individual')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schools', models.ManyToManyField(blank=True, to='core.school')),
                ('transfer_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_details', to='core.transferrecord')),
            ],
        ),
    ]
