# Generated by Django 5.2.1 on 2025-05-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_record_momo_option_remove_record_record_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('general', 'General'), ('specific', 'Specific')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='contribution',
            name='schools',
            field=models.ManyToManyField(blank=True, to='core.school'),
        ),
    ]
