# Generated by Django 5.2.1 on 2025-05-31 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_contribution_contribution_type_contribution_schools'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminReportsPage',
        ),
        migrations.RemoveField(
            model_name='momorecord',
            name='record',
        ),
        migrations.RemoveField(
            model_name='momorecord',
            name='schools',
        ),
        migrations.RemoveField(
            model_name='transferrecord',
            name='record',
        ),
        migrations.RemoveField(
            model_name='specifictransferdetail',
            name='schools',
        ),
        migrations.RemoveField(
            model_name='specifictransferdetail',
            name='transfer_record',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.RemoveField(
            model_name='transfercomment',
            name='transfer',
        ),
        migrations.DeleteModel(
            name='MomoRecord',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='SpecificTransferDetail',
        ),
        migrations.DeleteModel(
            name='TransferRecord',
        ),
        migrations.DeleteModel(
            name='TransferComment',
        ),
        migrations.DeleteModel(
            name='Transfers_Received',
        ),
    ]
