# Generated by Django 5.2.1 on 2025-06-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_transferreceived_delete_contribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferreceived',
            name='NumberOfPayments',
        ),
        migrations.AlterField(
            model_name='transferreceived',
            name='AccountNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transferreceived',
            name='Donor',
            field=models.CharField(choices=[('METRO WORLD CHILD', 'METRO WORLD CHILD'), ('Indiv through MoMo', 'Indiv through MoMo'), ('IREMBO', 'IREMBO'), ('MTN RWANDACELL LTD', 'MTN RWANDACELL LTD')], max_length=50),
        ),
    ]
