# Generated by Django 5.2.1 on 2025-06-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_transferreceived_numberofpayments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferreceived',
            name='Donor',
            field=models.CharField(max_length=200),
        ),
    ]
