# Generated by Django 5.2 on 2025-06-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_transferreceived_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashedDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distributed_on', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrashedSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrashedTransferReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SchoolCode', models.CharField(blank=True, max_length=100)),
                ('Donor', models.CharField(max_length=200)),
                ('Total_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contribution_type', models.CharField(max_length=50)),
                ('AccountNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('NumberOfTransactions', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='transferreceived',
            name='contribution_type',
            field=models.CharField(choices=[('local_transfer', 'Local Transfer'), ('momo', 'MoMo'), ('international_transfer', 'International Transfer'), ('lemitance', 'Lemitance')], default='local_transfer', max_length=50),
        ),
    ]
