# Generated by Django 5.2 on 2025-06-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_trasheddistribution_trashedschool_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferreceived',
            old_name='Total_Amount',
            new_name='Amount',
        ),
        migrations.RenameField(
            model_name='trashedtransferreceived',
            old_name='Total_Amount',
            new_name='Amount',
        ),
    ]
