# Generated by Django 5.2 on 2025-06-24 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_pendingdistributiondeletion_pendingschooldeletion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trasheddistribution',
            old_name='amount',
            new_name='Amount',
        ),
        migrations.RenameField(
            model_name='trasheddistribution',
            old_name='deleted_at',
            new_name='deleted_on',
        ),
        migrations.RemoveField(
            model_name='trasheddistribution',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='trasheddistribution',
            name='school_name',
        ),
        migrations.AddField(
            model_name='trasheddistribution',
            name='School',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school'),
        ),
        migrations.AddField(
            model_name='trasheddistribution',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trasheddistribution',
            name='original_distribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.distribution'),
        ),
        migrations.AlterField(
            model_name='pendingdistributiondeletion',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trasheddistribution',
            name='distributed_on',
            field=models.DateField(),
        ),
    ]
