# Generated by Django 5.2.1 on 2025-06-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_amount_trasheddistribution_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingdistributiondeletion',
            name='distribution',
        ),
        migrations.RemoveField(
            model_name='pendingdistributiondeletion',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='pendingschooldeletion',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='pendingschooldeletion',
            name='school',
        ),
        migrations.RemoveField(
            model_name='pendingtransferreceiveddeletion',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='pendingtransferreceiveddeletion',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='trasheddistribution',
            name='School',
        ),
        migrations.RemoveField(
            model_name='trasheddistribution',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='trasheddistribution',
            name='original_distribution',
        ),
        migrations.DeleteModel(
            name='TrashedSchool',
        ),
        migrations.DeleteModel(
            name='TrashedTransferReceived',
        ),
        migrations.DeleteModel(
            name='PendingDistributionDeletion',
        ),
        migrations.DeleteModel(
            name='PendingSchoolDeletion',
        ),
        migrations.DeleteModel(
            name='PendingTransferReceivedDeletion',
        ),
        migrations.DeleteModel(
            name='TrashedDistribution',
        ),
    ]
