# Generated by Django 5.2 on 2025-06-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_pendingdistributiondeletion_distribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferreceived',
            name='delete_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferreceived',
            name='delete_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Deletion'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='transferreceived',
            name='contribution_type',
            field=models.CharField(blank=True, choices=[('local_transfer', 'Local Transfer'), ('momo', 'MoMo'), ('international_transfer', 'International Transfer'), ('lemitance', 'Lemitance')], max_length=50, null=True),
        ),
    ]
