# Generated by Django 5.2 on 2025-06-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_transferreceived_delete_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='delete_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='delete_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('deleted', 'Deleted')], default='active', max_length=10),
        ),
    ]
