# Generated by Django 5.2 on 2025-06-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_distribution_delete_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='delete_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='delete_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending')], default='active', max_length=20),
        ),
    ]
