# Generated by Django 5.2 on 2025-06-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_school_delete_reason_school_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='delete_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Deletion'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
    ]
