# Generated by Django 5.2 on 2025-07-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_school_delete_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferreceived',
            name='AccountNumber',
        ),
        migrations.AddField(
            model_name='school',
            name='AccountNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
