# Generated by Django 5.2 on 2025-07-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_transferreceived_accountnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
