version: '3.8'

services:
  backend:
    build: ./dusangire_backend
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=dusangire-db
      - DB_USER=postgres
      - DB_PASSWORD=1234567890
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  frontend:
    build: ./dusangire-frontend
    ports:
      - "3000:5173" # Changed back to original port
    volumes:
      - ./dusangire-frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    working_dir: /app
    command: npm run dev -- --host
    depends_on:
      - backend

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dusangire-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
    ports:
      - "5432:5432"

volumes:
  postgres_data:
